version: '3.9'

services:
  postgres-db:
    image: postgres:15
    container_name: car-showroom-api
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CAR_SHOWROOM_DB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: